services:
  postgres:
    image: postgres:latest
    env_file:
      - .env.postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.pgadmin
    ports:
      - '5050:80'

volumes:
  postgres_data:
